"""
Diagnostic: validate the ARX -> physical-parameter recovery
(`ernesto.adaptation.ARX_1RC.theta_to_physical_1RC`) against synthetic data
where the true (R0, R1, C1, OCV) are known exactly.

Ground truth is generated by simulating the *same* backward-Euler recursion
used by the actual digital twin
(`ernesto.digital_twin.battery_models.electrical.ecm.FirstOrderThevenin
.step_current_driven`), driven by a PRBS-like current profile, with known
injected parameters. That synthetic (voltage, current) trace is then fed
through the same RLS + theta_to_physical_1RC pipeline used in production
(`ernesto.adaptation.arx_rls_estimator.ARXRLS1RCEstimator`) and the
recovered parameters are compared to the injected ones.

This isolates two questions that real ground data cannot answer cleanly:

1. Is the ARX regression + physical-parameter inversion mathematically
   correct at all, when everything else (sampling time, sign convention,
   real cell nonlinearity) is controlled for? Run with the *correct* Ts
   (matching the true simulation dt).
2. Does the Ts mis-configuration found by `arx_forgetting_sweep.py` (yaml
   says Ts=1s, real data is sampled at 0.1s) reproduce the same ~10x bias
   in a fully controlled, noise-free setting -- i.e. is that finding a
   property of the *code*, not an artifact of the real dataset? Run with a
   deliberately wrong Ts (10x off) and compare.

It also separately checks, at the correct Ts, how large the discrepancy is
between the *exact* discretization `theta_to_physical_1RC` assumes
(`alpha = exp(-Ts/tau1)`) and the *backward-Euler* discretization the
digital twin actually integrates with, by sweeping the dt/tau1 ratio -- this
is "bug 2" in the plan, evaluated on its own rather than conflated with the
Ts mis-configuration.

Usage:
    python scripts/arx_synthetic_validation.py [--out-dir DIR]
"""
import argparse
import os
import sys

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ernesto.adaptation.rls import RLS
from ernesto.adaptation.ARX_1RC import theta_to_physical_1RC

RNG_SEED = 42


def generate_prbs_current(n, dt, i_max=20.0, min_hold_s=2.0, max_hold_s=60.0, rng=None):
    """Block-wise random +/-i_max current, hold durations drawn uniformly
    in [min_hold_s, max_hold_s], similar in character to
    data/ground/online_learning/region_shift_validation_new.csv (which
    switches sign roughly every ~50s on average over its 626k samples at
    dt=0.1s)."""
    rng = rng or np.random.default_rng(RNG_SEED)
    i = np.empty(n, dtype=float)
    k = 0
    sign = rng.choice([-1.0, 1.0])
    while k < n:
        hold_samples = max(1, int(rng.uniform(min_hold_s, max_hold_s) / dt))
        i[k:k + hold_samples] = sign * i_max
        k += hold_samples
        sign *= -1.0
    return i[:n]


def simulate_true_ecm(i_used, dt, r0, r1, c1, ocv):
    """Exact replica of FirstOrderThevenin.step_current_driven's backward-Euler
    recursion (ecm.py), for constant true parameters."""
    n = len(i_used)
    v = np.empty(n, dtype=float)
    v_rc = 0.0
    for k in range(n):
        v_r0 = i_used[k] * r0
        v_rc = (v_rc / dt + i_used[k] / c1) / (1.0 / dt + 1.0 / (c1 * r1))
        v[k] = ocv - v_r0 - v_rc
    return v


def recover_parameters(v, i_used, Ts, forgetting_factor=0.999, P0_scale=1e9, warmup=20):
    n = len(v)
    rls = RLS(n_params=4, theta0=np.zeros(4), P0_scale=P0_scale, forgetting_factor=forgetting_factor)
    r0h = np.full(n, np.nan)
    r1h = np.full(n, np.nan)
    c1h = np.full(n, np.nan)
    ocvh = np.full(n, np.nan)

    for k in range(1, n):
        phi = np.array([v[k - 1], i_used[k], i_used[k - 1], 1.0])
        theta, _err, _gain = rls.update(phi, v[k])
        if k < warmup:
            continue
        physical = theta_to_physical_1RC(theta, Ts)
        if physical["valid"]:
            r0h[k], r1h[k], c1h[k], ocvh[k] = (
                physical["R0"], physical["R1"], physical["C1"], physical["OCV"])
        elif k > 0 and np.isfinite(r0h[k - 1]):
            r0h[k], r1h[k], c1h[k], ocvh[k] = r0h[k - 1], r1h[k - 1], c1h[k - 1], ocvh[k - 1]

    return r0h, r1h, c1h, ocvh


def pct_err(estimate, truth):
    return 100.0 * (estimate - truth) / truth


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="arx_synthetic_output")
    parser.add_argument("--duration-s", type=float, default=20000.0)
    parser.add_argument("--dt", type=float, default=0.1, help="true simulation/sampling step [s]")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    dt = args.dt
    n = int(args.duration_s / dt)

    # Ground truth, chosen close to what arx_forgetting_sweep.py recovered
    # from the real PRBS file at the corrected Ts (median R0~7.4 mOhm,
    # R1~3.0 mOhm, C1~12000 F, OCV~3.86 V).
    R0_TRUE, R1_TRUE, C1_TRUE, OCV_TRUE = 0.0074, 0.0030, 12000.0, 3.86
    tau1_true = R1_TRUE * C1_TRUE
    print(f"True params: R0={R0_TRUE} ohm, R1={R1_TRUE} ohm, C1={C1_TRUE} F, "
          f"OCV={OCV_TRUE} V, tau1={tau1_true:.1f} s, dt/tau1={dt/tau1_true:.4g}")

    rng = np.random.default_rng(RNG_SEED)
    i_used = generate_prbs_current(n, dt, i_max=20.0, min_hold_s=5.0, max_hold_s=100.0, rng=rng)
    v_true = simulate_true_ecm(i_used, dt, R0_TRUE, R1_TRUE, C1_TRUE, OCV_TRUE)

    # ---- Test 1: correct Ts (matches true dt) ----
    r0h, r1h, c1h, ocvh = recover_parameters(v_true, i_used, Ts=dt)
    tail = slice(n // 2, None)  # let RLS settle before judging steady-state recovery
    print("\n=== Test 1: Ts = true dt (correct) ===")
    for name, hist, truth in [("R0", r0h, R0_TRUE), ("R1", r1h, R1_TRUE),
                               ("C1", c1h, C1_TRUE), ("OCV", ocvh, OCV_TRUE)]:
        est = np.nanmedian(hist[tail])
        print(f"  {name}: recovered={est:.6g}  true={truth:.6g}  error={pct_err(est, truth):+.2f}%")

    # ---- Test 2: wrong Ts, 10x off (reproducing the yaml misconfiguration) ----
    Ts_wrong = dt * 10.0
    r0h_w, r1h_w, c1h_w, ocvh_w = recover_parameters(v_true, i_used, Ts=Ts_wrong)
    print(f"\n=== Test 2: Ts = {Ts_wrong} (10x the true dt={dt}, mirrors yaml Ts=1 vs real 0.1s) ===")
    for name, hist, truth in [("R0", r0h_w, R0_TRUE), ("R1", r1h_w, R1_TRUE),
                               ("C1", c1h_w, C1_TRUE), ("OCV", ocvh_w, OCV_TRUE)]:
        est = np.nanmedian(hist[tail])
        print(f"  {name}: recovered={est:.6g}  true={truth:.6g}  error={pct_err(est, truth):+.2f}%")

    # ---- Test 3: backward-Euler vs exact-discretization mismatch alone,
    #      at correct Ts, sweeping dt/tau1 ---------------------------------
    print("\n=== Test 3: exact-vs-backward-Euler pole mismatch alone (correct Ts each time) ===")
    print("  dt/tau1   alpha_exact   alpha_BE      rel_diff")
    for tau1_test in [tau1_true, 50.0, 5.0, 1.0, 0.3]:
        ratio = dt / tau1_test
        alpha_exact = np.exp(-ratio)
        alpha_be = 1.0 / (1.0 + ratio)
        rel_diff = (alpha_be - alpha_exact) / alpha_exact
        print(f"  {ratio:7.4f}   {alpha_exact:.6f}     {alpha_be:.6f}    {rel_diff:+.3e}")

    # ---- Plots ----
    t = np.arange(n) * dt
    fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
    axes[0].plot(t, v_true, lw=0.7)
    axes[0].set_ylabel("v_true [V]")
    axes[0].set_title("Synthetic PRBS ground truth")
    axes[0].grid(alpha=0.3)

    axes[1].plot(t, c1h, label="Ts=true dt (correct)", lw=0.9)
    axes[1].plot(t, c1h_w, label=f"Ts={Ts_wrong} (10x too large)", lw=0.9)
    axes[1].axhline(C1_TRUE, color="k", ls="--", lw=1, label="true C1")
    axes[1].set_ylabel("C1 [F]")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    axes[2].plot(t, ocvh, label="Ts=true dt (correct)", lw=0.9)
    axes[2].plot(t, ocvh_w, label=f"Ts={Ts_wrong} (10x too large)", lw=0.9)
    axes[2].axhline(OCV_TRUE, color="k", ls="--", lw=1, label="true OCV")
    axes[2].set_ylabel("OCV [V]")
    axes[2].set_xlabel("time [s]")
    axes[2].legend()
    axes[2].grid(alpha=0.3)

    fig.tight_layout()
    fig.savefig(os.path.join(args.out_dir, "synthetic_recovery.png"), dpi=130)
    print(f"\nPlot written to {args.out_dir}/synthetic_recovery.png")


if __name__ == "__main__":
    main()
