
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT CHARGE CRATE DISCHARGE FOR HOLD HOURS MINUTES NUMBER OR RATIO REST SECONDS UNIT UNTIL\n        command : DISCHARGE what\n        \n        command : CHARGE what\n        \n        command : REST time\n        \n        command : HOLD what\n        \n        what : AT rate time\n        \n        rate : CRATE RATIO NUMBER\n             | NUMBER CRATE\n             | NUMBER UNIT\n        \n        until_rate : UNTIL CRATE RATIO NUMBER\n                   | UNTIL NUMBER CRATE\n                   | UNTIL NUMBER UNIT\n        \n        time : duration\n             | until_rate\n             | duration OR until_rate\n             | until_rate OR duration\n        \n        duration : FOR NUMBER HOURS\n                 | FOR NUMBER MINUTES\n                 | FOR NUMBER SECONDS\n        '
    
_lr_action_items = {'DISCHARGE':([0,],[2,]),'CHARGE':([0,],[3,]),'REST':([0,],[4,]),'HOLD':([0,],[5,]),'$end':([1,6,8,9,10,11,14,23,27,28,29,30,31,33,34,36,],[0,-1,-2,-3,-12,-13,-4,-5,-14,-15,-16,-17,-18,-10,-11,-9,]),'AT':([2,3,5,],[7,7,7,]),'FOR':([4,15,19,25,26,35,],[12,12,12,-7,-8,-6,]),'UNTIL':([4,15,18,25,26,35,],[13,13,13,-7,-8,-6,]),'CRATE':([7,13,17,22,],[16,21,25,33,]),'NUMBER':([7,12,13,24,32,],[17,20,22,35,36,]),'OR':([10,11,29,30,31,33,34,36,],[18,19,-16,-17,-18,-10,-11,-9,]),'RATIO':([16,21,],[24,32,]),'UNIT':([17,22,],[26,34,]),'HOURS':([20,],[29,]),'MINUTES':([20,],[30,]),'SECONDS':([20,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'what':([2,3,5,],[6,8,14,]),'time':([4,15,],[9,23,]),'duration':([4,15,19,],[10,10,28,]),'until_rate':([4,15,18,],[11,11,27,]),'rate':([7,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> DISCHARGE what','command',2,'p_command_discharge','parser.py',28),
  ('command -> CHARGE what','command',2,'p_command_charge','parser.py',35),
  ('command -> REST time','command',2,'p_command_rest','parser.py',42),
  ('command -> HOLD what','command',2,'p_command_hold','parser.py',49),
  ('what -> AT rate time','what',3,'p_command_what','parser.py',56),
  ('rate -> CRATE RATIO NUMBER','rate',3,'p_rate','parser.py',62),
  ('rate -> NUMBER CRATE','rate',2,'p_rate','parser.py',63),
  ('rate -> NUMBER UNIT','rate',2,'p_rate','parser.py',64),
  ('until_rate -> UNTIL CRATE RATIO NUMBER','until_rate',4,'p_until_rate','parser.py',77),
  ('until_rate -> UNTIL NUMBER CRATE','until_rate',3,'p_until_rate','parser.py',78),
  ('until_rate -> UNTIL NUMBER UNIT','until_rate',3,'p_until_rate','parser.py',79),
  ('time -> duration','time',1,'p_time','parser.py',91),
  ('time -> until_rate','time',1,'p_time','parser.py',92),
  ('time -> duration OR until_rate','time',3,'p_time','parser.py',93),
  ('time -> until_rate OR duration','time',3,'p_time','parser.py',94),
  ('duration -> FOR NUMBER HOURS','duration',3,'p_for_duration','parser.py',103),
  ('duration -> FOR NUMBER MINUTES','duration',3,'p_for_duration','parser.py',104),
  ('duration -> FOR NUMBER SECONDS','duration',3,'p_for_duration','parser.py',105),
]
